version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: medcom_db
    restart: always
    environment:
      POSTGRES_USER: medcom
      POSTGRES_PASSWORD: medcom123
      POSTGRES_DB: medcom_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: back_end_postgres
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medcom_db
      SPRING_DATASOURCE_USERNAME: medcom
      SPRING_DATASOURCE_PASSWORD: medcom123
    ports:
      - "8080:8080"

volumes:
  postgres_data:
