version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-medcom
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  medcom_backend:
    build:
      context: .
    container_name: medcom_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  custom_network:
    driver: bridge