spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medcom_db
    username: medcom
    password: medcom123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    ignore-migration-patterns: "future,missing"
    validate-on-migrate: false
    locations: classpath:db/migration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
application:
  security:
    app:
      frontend-path: ${FRONTEND_PATH:localhost}
    jwt:
      secret-key: ${SECRET_KEY_TOKEN:ZTkxZTQyZDc2MDU3ZDU4ZDFkYTM3MjVkZDU5NTM1ZDY=}
      expiration: 1800000 # 30 min
      refresh-token:
        expiration: 7200000 # 2 hrs