spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/medcom_db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
