spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/medcom_db
    username: medcom
    password: medcom123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    ignore-migration-patterns: "future,missing"
    validate-on-migrate: false
    locations: classpath:db/migration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
